version: '3.8'

services:
  web_server1:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SERVER_ID=WebServer
    expose:
      - "5000"
  