version: '3.8'

services:
  
  web_server:
    image: myapp:v4  # replace with your actual web server image
    environment:
      - SERVER_ID=WebServer
    expose:
      - "5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
