version: '3.8'

services:
  load_balancer:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SERVER_ID=LoadBalancer

  web_server:
    image: web_server_image  # replace with your actual web server image
    environment:
      - SERVER_ID=WebServer
    expose:
      - "5000"
