name: Python Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5000:5000

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub if credentials are provided
      run: |
        if [ -n "${{ secrets.DOCKER_USERNAME }}" ] && [ -n "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        fi

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest
    
    - name: List Docker images
      run: docker images
    
    - name: Start Docker Compose services
      run: docker-compose up -d

    - name: List running Docker containers
      run: docker ps -a

    - name: Wait for services to be ready
      run: sleep 10  # Adjust the sleep time if necessary
    
    - name: Run tests
      run: docker-compose exec -T web_server pytest
    
    - name: Shut down Docker Compose services
      run: docker-compose down
